### ISSUE TITLE
MBS Consulting Report Author name error

### ISSUE THREAD

**Issue by dedi0003** [robjhyndman/MonashEBSTemplates#12]
Hi Prof, I tried to knit the template report but end up with this error message:

{{\sf \Large \textbf { Marie Curie}\\\sf \large Nobel Prize, PhD\\[0.\ETC.
! Paragraph ended before \author  was complete.
<to be read again> 
                   \par 
l.203 

I did not change anything to the template, just tried to knit it. If I delete the author field, it can knit the pdf

**Comment by robjhyndman** [comment]
Found the bug and fixed it in https://github.com/robjhyndman/MonashEBSTemplates/commit/02f70047e211cf858e3844900c85d8fdfbd984be
