### ISSUE TITLE
Re-import Beamer theme?

### ISSUE THREAD

**Issue by eddelbuettel** [robjhyndman/MonashEBSTemplates#3]
This is a lovely package and quite coherent in its Markdown support for Monash EBS.  

But it feels weird that the Beamer is now "gone".  Given that the `binb` package is on CRAN, should this package maybe have an Imports: or Suggests: and bring the `binb::monash()` function back here?

**Comment by robjhyndman** [comment]
Yes, I probably should do that.

**Comment by eddelbuettel** [comment]
Sounds good. Let me know if there is anything we need to do. I guess having `binb::monash()` exported is all there is?

**Comment by robjhyndman** [comment]
I made a wrapper instead so `MonashEBSTemplates::slides()` is identical to `binb::monash()`.

Fixed in https://github.com/robjhyndman/MonashEBSTemplates/commit/14a9e922b167255af676ed0650605ccb50130d08

**Comment by eddelbuettel** [comment]
All good then, so closing this.
